### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by donglv8889** [blueset/FanfouBot#1]
telegram点击同意授权后显示 login failed。无法使用电磁炉。
在饭否上搜了一下好像依然有人在使用telegram电磁炉发饭……想搞清楚为什么自己无法登陆……

**Comment by ifsc01** [comment]
login_failed

**Comment by ifsc01** [comment]
https://github.com/lidashuang/fanfou-telegram-bot @donglv8889

**Comment by blueset** [comment]
感谢汇报，现已尝试修复。
